Cargo.lock, Dockerfile, raiko-guest/config/raiko-guest.manifest.template, raiko-host/src/prover/context.rs, raiko-host/src/prover/execution.rs, raiko-host/src/prover/prepare_input.rs, raiko-host/src/prover/proof/sgx.rs, raiko-host/src/prover/server.rs, scripts/build-and-push-image.sh
=> fix: remove cache anyway

lib/src/execution/ethereum.rs, lib/src/taiko/execute.rs, primitives/src/ethers.rs, primitives/src/transactions/ethereum.rs
* Add support for EIP-4844 transaction type
* Update dependencies and implement EIP-4844
=> hotfix: support eip4844 transaction(type3) (#26)

host/src/host/host.rs, lib/src/consts.rs, lib/src/protocol_instance.rs, prove_block.sh
Syncing https://github.com/taikoxyz/raiko/pull/76/files
=> use timestamp based slot num to query blob

.github/workflows/ci.yml, host/src/host/host.rs, host/src/host/provider_db.rs, host/src/metrics.rs, host/src/prover/execution.rs, lib/src/builder/execute.rs, lib/src/lib.rs
99% of time of the witness generation is spent in RPC calls. At least when the node is remote. Hopefully when the node is local it is very fast, but still to be tested.
=> Performance metrics

provers/sp1/prover/src/lib.rs
360s vs 390s in my machine (ryzen 7840hs)
=> pref: poseidon2 is slightly faster than blake3 by testing

Cargo.lock, Cargo.toml, host/Cargo.toml, host/src/main.rs, host/src/prover/execution.rs
just peak memory for different parts of the block proving process
=> add memory statistics

Cargo.lock, Cargo.toml, host/Cargo.toml, host/src/execution.rs, host/src/main.rs, provers/risc0/guest/Cargo.lock, provers/risc0/guest/Cargo.toml, provers/risc0/src/lib.rs, provers/risc0/src/snarks.rs
changes
1. update risc0 to new version for bonsai running
2. rename output to proof for easy integration
3. add env_logger for info print.
4. few code refines
=> update risc0 dependency to 0.21.0 to run bonsai

host/src/provider_db.rs
Reduces the number of RPC calls for accounts from 3 to 2 (or even 1 if code fetching can be skipped when we know the code hash is empty).
I left the old code in for now because I see it working faster, but who knows how it might behave in different scenario's.
=> Use get_proof in account data fetching to reduce number of RPC calls

lib/src/taiko_utils.rs, provers/sgx/prover/src/lib.rs
Diverage point of a7 & unstable.
See https://github.com/taikoxyz/raiko/pull/142
=> align calldata path check with client

host/src/request.rs, makefile, pipeline/Cargo.toml, provers/risc0/driver/Cargo.toml, provers/risc0/driver/src/lib.rs, provers/sp1/driver/src/lib.rs
also a workaround for prover configs not working on unstable right now
=> pipeline small fixes + makefile

README_Docker_and_RA.md
=> chore(docs): update info

host/config/config.json, host/src/request.rs, script/prove-block.sh
Fix loading of prover specific configs from config files and API params
=> Prover config loading fix

lib/src/builder/execute.rs, prove_block.sh
same as https://github.com/taikoxyz/raiko/pull/184
=> fix(raiko): fix sticky invalid tx state [A7]

.github/workflows/ci.yml, Cargo.lock, README.md, lib/Cargo.toml, lib/src/builder/execute.rs
Useful for debugging differences in block execution between raiko and other nodes as we've found out now.
=> feat(raiko): add tracer support

README_Docker_and_RA.md
fix #154
Added recommended minimum memory allocation for SGX.
Added access to the list of compatible CPUs.
=> Update README_Docker_and_RA.md to Add SGX Recommended Specs

Cargo.toml
Small PR to continue reading our imports sane.
=> chore(raiko): reorg cargo imports

docker/docker-compose.metrics.yml, host/src/server/api/v1/proof.rs
Fix ports exposure in compose file
Fix concurrent request counting for all exit points
=> fix: metrics docker fix

Dockerfile, docker/docker-compose.yml, docker/entrypoint.sh, lib/src/consts.rs, provers/sgx/setup/src/app_args.rs, provers/sgx/setup/src/setup_bootstrap.rs, script/publish-image.sh
Will dev k8s build in another branch and merge once it done.
=> chore(raiko): revert docker build changes

docker/entrypoint.sh, lib/src/consts.rs, provers/sgx/setup/src/app_args.rs, provers/sgx/setup/src/setup_bootstrap.rs, script/publish-image.sh
- get config from spec file when setup
=> fix: docker stuff

harness/core/src/assert.rs, harness/core/src/lib.rs, harness/macro/src/lib.rs
Small code enhancements and lint fixes
=> refactor(harness): small code readability and lint fixes

provers/risc0/driver/src/bonsai.rs, provers/risc0/driver/src/lib.rs
Add cancellation support to bonsai network prover
=> feat(risc0): add cancellation to bonsai

provers/sp1/driver/src/lib.rs
Add mock support for sp1 cancellation
=> feat(sp1): add cancellation support

docs/README_Docker_and_RA.md
closes #308 , closes #173 , closes #172, closes #130
=> feat(docs): more improvements

Dockerfile.zk
refine zk image build logic & shrink the image size
=> feat(raiko): refine zk image build logic & shrink the image size

docs/README_Docker_and_RA.md
As the taiko-mono has been upgraded to protocol-v0.10.0, it is better to point directly to the correct script file.  There are also some minor modifications.
=> fix(raiko): updated README_Docker_and_RA.md with minor changes

.github/workflows/ci-all.yml
=> fix(repo): don't run on draft

docs/README_Docker_and_RA.md
=> feat(docs): docs improvements

taskdb/Cargo.toml
=> fix: tencentcloud redis doesnot support client cmd

reqpool/src/backend.rs, reqpool/src/pool.rs
Resolve https://github.com/taikoxyz/raiko/issues/464
=> fix(reqpool): filter type-error items when list

core/src/lib.rs, core/src/preflight/mod.rs, core/src/preflight/util.rs, lib/src/builder.rs, lib/src/input.rs, lib/src/input/pacaya.rs, lib/src/protocol_instance.rs, lib/src/utils.rs
revert due to protocol changed.
=> Revert pacaya dev align

script/build.sh
Noticed a small typo in a comment—"wannt" should be "want." Fixed it for clarity.
=> chore(script): fix comment

Cargo.lock, Cargo.toml, host/config/chain_spec_list_default.json, host/config/chain_spec_list_devnet.json, lib/src/protocol_instance.rs, reqactor/src/backend.rs
https://github.com/taikoxyz/taiko-reth/commit/043668882483120535b85e501d460ba4fd1792bc
https://github.com/taikoxyz/alloy/pull/3
=> feat: add alloy dependencies for v0.1.4-patch

Cargo.lock, Cargo.toml, lib/Cargo.toml, lib/src/protocol_instance.rs, provers/risc0/guest/Cargo.lock, provers/sp1/guest/Cargo.lock
=> feat: add pretty diff print when mismatch

docs/README_Docker_and_RA.md, script/prove-batch.sh
usage: ./prove-batch.sh  taiko_a7 pivot 1306738,3606914
=> feat(raiko): update script to support batch prove

reqactor/src/queue.rs, script/test_aggregation_priority.py
Add medium priority queue; enhance test_aggregation_priority monitor display.
=> feat: add medium priority queue
