taikoxyz/raiko

raiko-guest/src/one_shot.rs
Update quote before output, otherwise quote misses the reportData.
=> Update quote before output

lib/src/execution/ethereum.rs, lib/src/taiko/execute.rs, primitives/src/ethers.rs, primitives/src/transactions/ethereum.rs
This is a temporary solution. Holesky updated to Cankun few hours ago, but Raiko didn't know the type3 transaction.
=> hotfix: support eip4844 transaction(type3)

lib/src/execution/ethereum.rs, lib/src/taiko/execute.rs, primitives/src/ethers.rs, primitives/src/transactions/ethereum.rs
* Add support for EIP-4844 transaction type
* Update dependencies and implement EIP-4844
=> hotfix: support eip4844 transaction(type3) (#26)

primitives/src/mpt.rs, raiko-host/src/prover/proof/risc0/mod.rs
=> fix: enable the mpt cache

.gitignore, .vscode/settings.json, Cargo.lock, lib/src/consts.rs, lib/src/protocol_instance.rs, lib/src/taiko_utils.rs, raiko-guests/risc0/guest/Cargo.lock, raiko-guests/succinct/Cargo.lock, run_bonsai.sh
The a7 use eip712 sign.
A problem is it replaces the a6 sig, which makes it incompatible with a6. Maybe no problem as a6 will be gone later.
=> enable eip712 sign pi

lib/src/consts.rs, lib/src/host/provider/rpc_provider.rs, lib/src/taiko/host.rs, primitives/src/taiko/consts.rs
Because in mainnet, the slot number != block height
=> Use timestamp to slot instead of block height to query blob.

prove_block.sh, provers/sgx/prover/src/lib.rs
Allow the SGX prover to be run with 3 different commands:
- Setup
- Bootstrap
- Prove
I have tested this code in SGX and it seems to work, even though I heard there may be some problems with how the private key is handled.
=> Introduce SGX subcommands

provers/sgx/config/raiko-guest.manifest.template, provers/sgx/guest/src/app_args.rs, provers/sgx/prover/src/lib.rs
use block_id.bin instead of input.bin to avoid race condition in concurrency use scenario.
=> fix input.bin concurrency issue

host/src/execution.rs, host/src/server.rs, provers/sgx/prover/src/lib.rs
The path to the local manifest was not updated, so the copy failed.
However, if you didn't check the output you would not have noticed because we did not check the status of the command, so if the manifest was already there from before a proof could actually be successfully generated and everything would look alright, though with an outdated manifest file. So I changed things so that the status is checked for all commands and raiko doesn't make it look like a proof was generated when an error is encountered during the proving.
=> Fix SGX manifest file path + better error handling

provers/sgx/guest/src/one_shot.rs, provers/sgx/prover/src/lib.rs
Return quote when client request bootstrap without proof (as bootstrap does not have it). Then caller can see the quote remotely, rather then open a local file.
Also change is_bootstrap to load_bootstrap to test if a bootstrap file is loadable, which is the 1st step of automatically register on-chain sgx id, ref: https://github.com/taikoxyz/raiko/issues/108
=> Show quote in bootstrap command and make loading bootsrap testable.

host/src/preflight.rs, host/src/provider_db.rs, lib/src/builder/execute.rs, lib/src/builder/mod.rs, lib/src/mem_db.rs
We can batch the accounts and storage data accesses if we optimistically execute transactions without waiting on the data, and keeping a list of all data that was accessed. Afterwards we can then batch request all accessed data and then re-execute the transactions to incrementally get the actual required data for a block.
So this trades off local CPU processing for more efficient RPC requests because now transactions need to be executed multiple times. For remote node accesses, this seems to be very much worth it with 5x - 10x faster input gathering compared to #111.
=> optimistic execution for even more RPC batching

README_Docker_and_RA.md
Add a missing `sudo` in the raiko docker prereqs install command snippet
=> Add missing `sudo`

lib/src/taiko_utils.rs
miss decompression in calldata path
=> hotfix: decompress txlist in calldata path.

lib/src/taiko_utils.rs, provers/sgx/prover/src/lib.rs
Align calldata checking logic with client.
However, in main branch, we should check the size before decompress. So, we make release tag from this PR, and after it, the A7 release branch will diverge from unstable.
=> hotfix: align calldata path check with client

host/config/config.json, lib/Cargo.toml, lib/src/protocol_instance.rs, provers/risc0/guest/Cargo.toml, provers/sgx/guest/Cargo.toml, provers/sp1/guest/Cargo.toml
Some problems in SGX and SP1 while proving with the kzg check, so I temporarily disabled them in those provers. Well actually it is currently always disabled because sgx is enabled in the workspace so it will always compile the lib with that feature on, so using features not exactly the best way to do these kind of prover specific things unfortunately.
In SGX (direct mode):
In SP1:
=> fix(lib): temporarily disable kzg check in sgx/sp1 provers

host/src/preflight.rs, host/src/raiko.rs, lib/src/builder/execute.rs, script/prove-block.sh
There's a couple of ways to clear the sticky tx state, not sure if this is the cleanest one but seems to work.
I think it's okay to set the list of warm addresses to empty without removing the addresses that should still be warm, but not 100% sure about this.
=> fix(raiko): fix sticky invalid tx state

provers/risc0/guest/src/mem.rs, provers/sp1/guest/src/mem.rs
https://docs.rs/libc/latest/libc/fn.calloc.html
```rust
pub fn calloc(nobj: size_t, size: size_t) -> *mut c_void;
```
=> fix: mismatch method signature of libc's calloc

.github/workflows/ci.yml, Cargo.lock, host/src/preflight.rs, lib/src/builder/execute.rs, lib/src/consts.rs, lib/src/mem_db.rs, lib/src/protocol_instance.rs, lib/src/utils.rs, pipeline/src/builder.rs, pipeline/src/executor.rs, pipeline/src/risc0_util.rs, primitives/src/eip4844.rs, primitives/src/mpt.rs, provers/risc0/guest/src/main.rs, provers/sgx/guest/Cargo.toml, provers/sgx/guest/src/one_shot.rs, provers/sgx/prover/src/sgx_register_utils.rs, provers/sp1/guest/src/main.rs
Fix some clippy pedantic lints and make clippy CI job fail on warnings
=> chore: pedantic lints

host/src/interfaces/error.rs, host/src/server/api/mod.rs, host/src/server/api/v1/mod.rs, host/src/server/api/v1/proof.rs
=> feat: always respond with 200 but include status key

Cargo.lock, Dockerfile, docker/docker-compose.yml, docker/entrypoint.sh, host/src/lib.rs, provers/sgx/prover/Cargo.toml, provers/sgx/prover/src/lib.rs, provers/sgx/prover/src/sgx_register_utils.rs, provers/sgx/setup/src/setup_bootstrap.rs
copy default chain_spec to chain_spec_list.docker.json, and let user to config this one instead of the default one which has impact to image_id (mrenclave). Also added corresponding script to config different rpc_urls.
=> feat(raiko): update docker build

docker/docker-compose.yml, docker/entrypoint.sh, host/config/chain_spec_list_default.json
=> feat(raiko): update chain spec

Cargo.lock, provers/sgx/setup/Cargo.toml, provers/sgx/setup/src/setup_bootstrap.rs
Share the registered specifications by sharing the persistent volume. We need to lock the entire setup process to prevent data races.
=> feat: lock the setup for sharing instance

README.md
Adding new lines between paragraphs and headings and code blocks.
Adding proper highlighting to code blocks and removing `$` symbol
=> chore(readme): update spacing and code block syntax

host/src/server/api/v1/proof.rs
Add guest request count and make concurrent request decrementation more ergonomic
=> fix(host): fix some metric tracking

.dockerignore, Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/interfaces.rs, core/src/lib.rs, core/src/preflight.rs, core/src/prover.rs, core/src/provider/db.rs, core/src/provider/mod.rs, core/src/provider/rpc.rs, host/Cargo.toml, host/src/bin/main.rs, host/src/interfaces.rs, host/src/interfaces/mod.rs, host/src/lib.rs, host/src/metrics.rs, host/src/server/api/v1/metrics.rs, host/src/server/api/v1/mod.rs, host/src/server/api/v1/proof.rs, host/src/server/mod.rs, lib/src/consts.rs, lib/src/protocol_instance.rs
Make host only responsible for running server and docs creation
=> refactor: move out core into separate crate

pipeline/src/builder.rs, pipeline/src/executor.rs, pipeline/src/lib.rs, pipeline/src/risc0_util.rs
Simplify some code branching and add messaging to unwraps
=> refactor(pipeline): make code more readable and handle unwraps

script/build.sh
Change the echo statement to print risc0 instead of sp1 for the risc0 branch
Use the risc0 toolchain for risc0 instead of using the sp1 toolchain
Whitespace formatting
=> chore(scripts): use risc0 toolchain instead of sp1 and fix typos

Dockerfile
Address workdir and consecutive run commands lints
=> chore(dockerfile): address dockerfile lints

host/src/server/api/v1/proof.rs
Transform option mapping into let else and guard clauses
=> refactor(host): simplify getting and setting cached files

.github/workflows/typo-check.yml, Cargo.lock, _typos.toml, core/src/lib.rs, core/src/prover.rs, host/src/server/api/v1/mod.rs, lib/src/input.rs, lib/src/protocol_instance.rs, provers/risc0/driver/src/bonsai.rs, provers/risc0/driver/src/lib.rs, provers/risc0/guest/Cargo.lock, provers/risc0/guest/src/main.rs, provers/sp1/driver/src/lib.rs, provers/sp1/guest/Cargo.lock, provers/sp1/guest/src/main.rs, provers/sp1/guest/src/zk_op.rs
The zk provers should return the `ProtocolInput` hash to match the onchain verifier, when it fails to generate `pi_hash` the proof should just fail and ZkVM should exit. In that case, the `GuestOutput::Failure` will never be used and currently it's not used reasonably so we should just remove the case.
```
pub enum GuestOutput {
Success {
header: AlloyConsensusHeader,
hash: B256,
},
Failure,
}
```
change to:
```
pub enum GuestOutput {
header: AlloyConsensusHeader,
hash: B256,
}
```
For verifier support, see https://github.com/taikoxyz/taiko-mono/pull/17215
=> feat(prover): change GuestOutput and the zk committed value for onchain verification

Cargo.lock, Cargo.toml, host/src/lib.rs, host/src/server/api/v2/proof.rs, task_manager/Cargo.toml, task_manager/src/adv_sqlite.rs, task_manager/src/lib.rs, task_manager/src/mem_db.rs, task_manager/tests/main.rs
@smtmfft Here are some changes I propose, also a raiko branch so both of us can collaborate
=> feat(task_db): sqlite and in memory abstraction

docs/README_Docker_and_RA.md
Adding update kernel version steps in README_Docker_and_RA.md
=> docs: update instruction to change kernel version in README_Docker_and_RA.md

Cargo.lock, lib/Cargo.toml, lib/src/prover.rs, provers/risc0/driver/src/bonsai.rs, provers/risc0/driver/src/lib.rs, provers/sp1/driver/src/lib.rs, tasks/src/adv_sqlite.rs, tasks/src/lib.rs, tasks/src/mem_db.rs
Fixes the issue of creating a runtime within a runtime by using async traits:
Issue sample:
```
thread 'tokio-runtime-worker' panicked at tasks/src/mem_db.rs:169:12:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
stack backtrace:
```
=> fix(lib,provers,tasks): move from sync to async trait

provers/risc0/driver/Cargo.toml, provers/risc0/driver/src/bonsai.rs, provers/risc0/driver/src/bonsai/auto_scaling.rs, provers/risc0/driver/src/lib.rs
1. use feature to enable auto-scaling
2. give enough time to heat up bonsai
3. use ref count to avoid shutdown with ongoing tasks.
To address some issues in #341
=> feat(raiko): refine auto-scaling

Cargo.lock, provers/risc0/driver/Cargo.toml, provers/risc0/driver/src/bonsai.rs, provers/risc0/driver/src/lib.rs, provers/sp1/driver/src/lib.rs
Use error return instead of panic! to avoid unclean status which leads to endless WIP status back to client.
Probably need more refines with API CI test @petarvujovic98 .
=> feat(raiko): refine error return to avoid incorrect status.

core/src/preflight/util.rs, provers/risc0/driver/src/bonsai.rs
=> feat(raiko): traversal to find inclusion block if none inclusion number is sent

docker/entrypoint.sh, host/src/proof.rs, host/src/server/api/v2/mod.rs
hotfix for client error message handling. #376 
Currently UnspecifiedFailureReason seems a easy fit for merely db storage.
I change it to error return, next I think we need refine the error msg db as we need to give clear error message to client.
=> fix(raiko): refine error return

Dockerfile, provers/sgx/config/sgx-guest.docker.manifest.template
New added crates use the number of cores for thread pool, and needs to get the correct number from cgroup file
=> fix: add cgroup&mountinfo for docker env

lib/src/builder.rs
We had an issue of block 380550 on our Mainnet when processing stress test. 
```console
2024-10-13T08:58:58.429218Z ERROR raiko_host::proof: There was an error with the core: There was an error with a guest prover: ProverError::GuestError `Condition failed: `self.input.block.state_ro
ot == state_root``
```
It told me, the state root of Raiko is different from Geth. My first impression is that there are differences in the modifications to Accounts during the execution of EVM. But...
I found that there was an unexpected `account-deleted` behavior in Raiko. 
And there are two transactions related to it in block 380550,
|no | role |value |
|---|-----|------|
| 969| to | 0 ETH|
| 977| to | 0.0001 ETH|
Because the first one received zero ETH, so it's `nonce` and `balance` weren't changed. But, …
=> fix: incorrect state transition handling

core/src/preflight/util.rs, docker/docker-compose.yml, docker/entrypoint.sh, host/src/bin/main.rs, lib/src/input.rs, lib/src/protocol_instance.rs, lib/src/utils.rs
support proposing multi-blocks within same proposal tx
=> feat(raiko): multi blocks in one proposal tx

core/src/preflight/mod.rs, host/src/lib.rs, host/src/server/api/v2/proof/cancel.rs, host/src/server/api/v2/proof/mod.rs, host/src/server/api/v3/proof/aggregate.rs, host/src/server/api/v3/proof/cancel.rs, host/src/server/api/v3/proof/mod.rs, lib/src/input.rs
This PR removes several implicit From implementations, which made type transformations implicit and not easy to understand without providing any benefits.
=> chore: remove redundant and implicit From impl

core/src/lib.rs, core/src/prover.rs, lib/src/consts.rs, lib/src/proof_type.rs, lib/src/protocol_instance.rs, provers/risc0/driver/src/lib.rs, provers/risc0/guest/src/main.rs, provers/sgx/guest/src/one_shot.rs, provers/sgx/setup/src/setup_bootstrap.rs, provers/sp1/driver/src/lib.rs, provers/sp1/driver/src/verifier.rs, provers/sp1/guest/src/main.rs
This PR make the follow-up changes of https://github.com/taikoxyz/raiko/pull/421#issue-2690366478 
> 2. Merge `Proof System ID` into `ProofType`, to eliminate redundant definitions and simplify the management of proof types for taskdb
> 
>     - [Proof System ID](https://github.com/keroro520/raiko/blob/7b374f137decffea8f92d8c2ab15c0e3a423939f/taskdb/src/adv_sqlite.rs#L57-L62), also known as "prover code"
>     - [Proof System ID `RISC0_PROVER_CODE = 3`](https://github.com/keroro520/raiko/blob/7b374f137decffea8f92d8c2ab15c0e3a423939f/provers/risc0/driver/src/lib.rs#L63)
>     - [Proof System ID `SP1_PROVER_CODE = 1`](https://github.com/keroro520/raiko/blob/7b374f137decffea8f92d8c2ab15c0e3a423939f/provers/sp1/driver/src/lib.rs#L30)
> 
> 3. Merge `VerifierType` into `ProofType`.
> 
>     - …
=> feat: union proof type relevant stuff

Cargo.lock, Cargo.toml, taskdb/Cargo.toml, taskdb/src/redis_db.rs
in k8s development, the redis sometimes restarts without awareness, add reconnect mechanism to avoid fatal errors.
=> feat(raiko): make redis able to re-connect

provers/sp1/driver/src/lib.rs
Fix off-chain sp1 aggregation proof verification error:
```
"2024-12-12T12:03:37.672895Z ERROR sp1_driver::proof_verify::remote_contract_verify: SP1 proof verification failed: Err(TransportError(ErrorResp(ErrorPayload { code: 3, message: "execution reverted", data: Some(RawValue("0x09bde339")) })))!"
```
=> fix(raiko): fix sp1 aggregation verification error

makefile
Add make help messages:
```
$ make
Usage:
make <target>
help             Display this help.
install          Install the project
guest            Build the guest binary
run              Run the project
test             Run the tests
integration      Run the integration tests
fmt              Run cargo fmt
clippy           Run cargo clippy
update           Run cargo update
```
=> feat(make): add make help message

host/src/server/api/mod.rs
The original implementation of check_max_body_size relied on the size_hint provided by Axum. However, we've encountered instances where check_max_body_size incorrectly returns a BAD_REQUEST response due to inaccurate size_hint values.
This commit changes to use `DefaultBodyLimit`, which is the suggested method by axum.
See also
- https://github.com/tokio-rs/axum/pull/1400
- https://github.com/tokio-rs/axum/pull/1397
=> fix(host): limit body size using DefaultBodyLimit

Cargo.lock, Cargo.toml, provers/risc0/driver/src/bonsai.rs, provers/sp1/driver/Cargo.toml, provers/sp1/driver/src/lib.rs
The block proof ELF is approximately 8 MB, and is being uploaded every time. Using an initialization-once approach to avoid redundant uploads
=> fix(raiko): avoid duplicate image uploads

host/src/interfaces.rs, host/src/lib.rs, host/src/proof.rs, host/src/server/api/admin.rs, host/src/server/api/mod.rs, host/src/server/api/util.rs, host/src/server/api/v1/proof.rs, host/src/server/api/v2/proof/mod.rs, host/src/server/api/v3/proof/aggregate/cancel.rs, host/src/server/api/v3/proof/mod.rs, taskdb/src/lib.rs
Add HTTP API "/admin/pause".
Clear pending tasks and cancel all running tasks and aggregation tasks when "/admin/pause" called.
---
TODOs in the future:
- [Cancelled tasks should be removed from running_tasks/aggregate_tasks](https://github.com/taikoxyz/raiko/pull/440/files#diff-527386fe2e859ee858305b0298d486712a574b764b108804f527fc1cf54b0a97R634-R635)
- [make sure all tasks are saved to database, including pending tasks.](https://github.com/taikoxyz/raiko/pull/440/files#diff-527386fe2e859ee858305b0298d486712a574b764b108804f527fc1cf54b0a97R471)
- https://github.com/taikoxyz/raiko/pull/440#discussion_r1897093468                 
- WorkingInProgress task can not be cancelled, actually.
- API for query task
- https://github.com/taikoxyz/raiko/pull/440#discussion_r1897219496
=> feat(host): impl API "/admin/pause"

Dockerfile.pccs
Bump the base image from ubuntu23 to ubuntu24
- The Ubuntu 23.04 release ("Lunar") reached end of life (EOL) in January 2024
- See also https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-is-installed/76691103#76691103
=> feat(Dockerfile.pccs): bump base image to ubuntu 24.04

script/install.sh
Running `rzup install` will install the latest versions of the Risc0 toolchain and tools. To avoid unintended breakage when new versions are released, pin them to working versions.
We want to release a new version of Rust (1.85.0) for building guests, but if we set it as latest `rzup install` will silently upgrade to it, potentially breaking compilation.
=> feat(raiko): pin the versions used of the risc0 tools

Cargo.lock, provers/sgx/prover/Cargo.toml, provers/sgx/prover/src/local_prover.rs
only linux supports memfd, we can use "Anonymous" tempfile instead of it
=> chore: use tempfile instead of memfd to cross platforms

host/src/bin/main.rs, host/src/lib.rs, host/tests/common/server.rs, reqactor/src/actor.rs, reqactor/src/backend.rs, reqactor/src/lib.rs, reqactor/src/queue.rs
Add a maximum queue size limit with a default value of 1000 to the Queue struct, now the actor will return a failed status when the queue is full.
=> feat: add a maximum queue size limit
